### ISSUE TITLE
官网标题点击问题（Official website title click question）

### ISSUE THREAD

**Issue by rennjiao** [IvorySQL/Ivory-www#34]
点击官网的标题不是很明显，点击的时候颜色变深了，所以看不清楚。希望能调整一下。
After clicking the title on the main page of the official website, the text becomes dark, and not easy to read.

**Comment by codeforall** [comment]
@rennjiao I have created a pull request to change the highlight and links color
https://github.com/IvorySQL/Ivory-www/pull/35
You can view the preview version at https://deploy-preview-35--ivorysql.netlify.app/
Please suggest if you are looking for different colors.
