### ISSUE TITLE
The description of the parameter (weekday) of the function (next_day) in the document is incorrect

### ISSUE THREAD

**Issue by liuxintang** [IvorySQL/Ivory-www#36]
## Bug Report
The description of the parameter (weekday) of the function (next_day) in the document is incorrect
### Browser
[e.g. chrome, safari]

### Expected behavior
The value of the parameter (weekday) should be 1 to 7, with 1 representing Sunday.
Please confirm and revise the description in the document.
### Actual behavior
In the document, the parameter (weekday) of the function (next_day) is noted as follows.
0 means Sunday.
![image](https://user-images.githubusercontent.com/99459384/158928936-017067a3-ce31-4728-8747-9e16637b8555.png)

However, when the parameter (weekday) is set to 0, there is an error in execution.
![image](https://user-images.githubusercontent.com/99459384/158928976-8fa79add-4d82-4c2b-9e23-dbbbd897280d.png)

After verification, the integer value of the parameter (weekday) is 1 to 7, not 0 to 6, 1 represents Sunday, the document is incorrect. the value of Oracle is also 1 to 7.
![image](https://user-images.githubusercontent.com/99459384/158929001-8ea17eab-3d79-4291-82ca-8a3e30eec783.png)

**Comment by grantzhou** [comment]
document fixed in #92
