### ISSUE TITLE
IvorySQL official website language switching

### ISSUE THREAD

**Issue by rennjiao** [IvorySQL/Ivory-www#61]
## Enhancement IvorySQL 1.5 official website has problems with language switching.
Chinese version cannot be switched to the English version

**Comment by grantzhou** [comment]
I tried and it is working, could you please try it again? Sometimes when the website was not fully loaded, there may have ridiculous behaviour.

**Comment by rennjiao** [comment]
We tried several times. It is not possible to switch between the homepage of the official website.

**Comment by YunheXu** [comment]
在中国大陆地区确实是无法打开英文版官网，因为会自动跳转/zh-CN/标签。截止到今日仍是如此。

**Comment by grantzhou** [comment]
> 浏览器优先语言为中文时确实是无法打开英文版官网，因为会自动跳转/zh-CN/标签。截止到今日仍是如此。 浏览器首选语言为非中文时是可以自由切换中英文的。

非常感谢您的回复，我们尽快修复这个问题

**Comment by DutMsn** [comment]
#104
